version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urldata
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: mishra/short-url
    depends_on:
      - mysql-local
    ports:
      - 8080:8080
      